<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nj_blog"
 *
 * Auto generated by Extension Builder 2013-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'njs Blog-System',
	'description' => 'Just another blog system.',
	'category' => 'plugin',
	'author' => 'Nico Jatzkowski',
	'author_email' => 'nj@n1coo.de',
	'author_company' => 'n1coo.de',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'fileadmin/user_upload/tx_njblog',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '6.2.0',
	'CGLcompliance' => '',
	'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => '',
);

?>